#!/bin/bash
# List details about all backups.

function getDf
{
    grep Mounted */df.out | head -n1
    grep mnt */df.out
}

function showDf
{
    getDf | sed '1 s/.*:/.:/' | sed "s/:/ /g;s/\/df\.out//g" | awk '{print $1, $3, $4, $5, $6}' | column -t
}

showDf
